services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_PASSWORD: 182801xarf
      POSTGRES_USER: encrypuser
      POSTGRES_DB: encryption
      POSTGRES_HOST: localhost
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

